# Generated by Django 3.2.8 on 2021-11-01 13:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ariza_holati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arizalar', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ariza',
            },
        ),
        migrations.CreateModel(
            name='Ariza_statusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Chet_tili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chet_tili',
            },
        ),
        migrations.CreateModel(
            name='Chet_tili_darajasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darajalar', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daraja',
            },
        ),
        migrations.CreateModel(
            name='Chet_tili_sertifikatlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sertifikat',
            },
        ),
        migrations.CreateModel(
            name='Erishgan_yutuqlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yutuqlar_nomi', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'yutuqlar',
            },
        ),
        migrations.CreateModel(
            name='Fuqarolik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuqarolik', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fuqarolik',
            },
        ),
        migrations.CreateModel(
            name='Ilmiy_yutuqlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yutuqlar_nomi', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ilmiy_yutuqlar',
            },
        ),
        migrations.CreateModel(
            name='Ilmiy_yutuqlar_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yutuqlar_turi', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'yutuqlar_turi',
            },
        ),
        migrations.CreateModel(
            name='Informatika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'informatika',
            },
        ),
        migrations.CreateModel(
            name='Ingliz_tili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ingliz_tili',
            },
        ),
        migrations.CreateModel(
            name='Millat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millat_nomi', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'millat',
            },
        ),
        migrations.CreateModel(
            name='Oquv_kursi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'oquv_kursi',
            },
        ),
        migrations.CreateModel(
            name='Oquv_yili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oquv_yili', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'oquv_yili',
            },
        ),
        migrations.CreateModel(
            name='OTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otm',
            },
        ),
        migrations.CreateModel(
            name='OTM_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otm_turi',
            },
        ),
        migrations.CreateModel(
            name='Ozbekiston_tarixi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ozbekiston',
            },
        ),
        migrations.CreateModel(
            name='Reyting_baho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reyting',
            },
        ),
        migrations.CreateModel(
            name='Stependiyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stependiya',
            },
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiya', models.CharField(max_length=50)),
                ('t_yil', models.IntegerField(default=1)),
                ('yosh', models.IntegerField(default=1)),
                ('pasport_seriya', models.CharField(max_length=30)),
                ('sertifikati', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('erishgan_yutuqlar', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('ilmiy_yutuqlar', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('chet_tili', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.chet_tili')),
                ('darajasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.chet_tili_darajasi')),
                ('fuqarolik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.fuqarolik')),
                ('informatika', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.informatika')),
                ('ingliz_tili', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.ingliz_tili')),
                ('millati', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.millat')),
                ('oquv_kursi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.oquv_kursi')),
                ('oquv_yili', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.oquv_yili')),
                ('otm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.otm')),
                ('ozbekiston_tarixi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.ozbekiston_tarixi')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.ariza_statusi')),
            ],
            options={
                'db_table': 'talaba',
            },
        ),
        migrations.CreateModel(
            name='Talim_shakli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talim_shakli_nomi', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'talim_shakli',
            },
        ),
        migrations.CreateModel(
            name='Talim_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talim_turi_nomi', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'talim_turi',
            },
        ),
        migrations.CreateModel(
            name='Talim_yonalishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonalish_nomi', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'talim_yonalishi',
            },
        ),
        migrations.CreateModel(
            name='Tanlov_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanlov_turi', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tanlov_turi',
            },
        ),
        migrations.CreateModel(
            name='Vazirlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vazirlik',
            },
        ),
        migrations.CreateModel(
            name='Viloyatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'viloyat',
            },
        ),
        migrations.CreateModel(
            name='Yangi_arizalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.ariza_statusi')),
                ('talaba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.talaba')),
            ],
            options={
                'db_table': 'yangi_ariza',
            },
        ),
        migrations.CreateModel(
            name='Tumanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('viloyat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.viloyatlar')),
            ],
            options={
                'db_table': 'tuman',
            },
        ),
        migrations.AddField(
            model_name='talaba',
            name='t_tuman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.tumanlar'),
        ),
        migrations.AddField(
            model_name='talaba',
            name='talim_shakli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.talim_shakli'),
        ),
        migrations.AddField(
            model_name='talaba',
            name='talim_turi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.talim_turi'),
        ),
        migrations.AddField(
            model_name='talaba',
            name='talim_yonalishi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.talim_yonalishi'),
        ),
        migrations.AddField(
            model_name='talaba',
            name='tugilgan_viloyat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.viloyatlar'),
        ),
        migrations.CreateModel(
            name='Rad_qilingan_arizalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.ariza_statusi')),
                ('talaba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.talaba')),
            ],
            options={
                'db_table': 'rad_ariza',
            },
        ),
        migrations.CreateModel(
            name='Qabul_qilingan_arizalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.ariza_statusi')),
                ('talaba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.talaba')),
            ],
            options={
                'db_table': 'qabul_ariza',
            },
        ),
        migrations.AddField(
            model_name='ozbekiston_tarixi',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.reyting_baho'),
        ),
        migrations.AddField(
            model_name='otm',
            name='otm_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.otm_turi'),
        ),
        migrations.AddField(
            model_name='otm',
            name='vazirlik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.vazirlik'),
        ),
        migrations.AddField(
            model_name='ingliz_tili',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.reyting_baho'),
        ),
        migrations.AddField(
            model_name='informatika',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.reyting_baho'),
        ),
        migrations.CreateModel(
            name='Administrator_royxati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xodimlar', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('otm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stipendiya.otm')),
            ],
            options={
                'db_table': 'xodim',
            },
        ),
    ]
